import type { CatalogueResponse } from "../types";

export const catalogueFixture: CatalogueResponse = {
  title: "Men",
  total: 12,
  page: 1,
  pageSize: 12,

  filters: [
    {
      id: "category",
      label: "Category",
      type: "checkbox",
      options: [
        { id: "t-shirts", label: "T-Shirts", value: "t-shirts" },
        { id: "hoodies", label: "Hoodies", value: "hoodies" },
        { id: "jackets", label: "Jackets", value: "jackets" },
        { id: "shirts", label: "Shirts", value: "shirts" },
        { id: "bottoms", label: "Bottoms", value: "bottoms" },
      ],
    },
    {
      id: "style",
      label: "Style",
      type: "checkbox",
      options: [
        { id: "casual", label: "Casual", value: "casual" },
        { id: "streetwear", label: "Streetwear", value: "streetwear" },
        { id: "everyday", label: "Everyday", value: "everyday" },
      ],
    },
    {
      id: "collection",
      label: "Collection",
      type: "checkbox",
      options: [
        { id: "new-arrivals", label: "New Arrivals", value: "new-arrivals" },
        { id: "limited-drops", label: "Drops", value: "limited-drops" },
        { id: "core", label: "Core Collection", value: "core" },
      ],
    },
    {
      id: "price",
      label: "Price",
      type: "price",
    },
  ],

  products: [
    {
      id: "derz-mens-001",
      name: "DERZ Essential Tee",
      slug: "derz-essential-tee",
      category: "T-Shirts",
      style: "everyday",
      collection: "core",
      price: 499,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-essential-tee",
      badge: "New",
    },
    {
      id: "derz-mens-002",
      name: "DERZ Oversized Hoodie",
      slug: "derz-oversized-hoodie",
      category: "Hoodies",
      style: "streetwear",
      collection: "core",
      price: 899,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-oversized-hoodie",
    },
    {
      id: "derz-mens-003",
      name: "DERZ Utility Jacket",
      slug: "derz-utility-jacket",
      category: "Jackets",
      style: "streetwear",
      collection: "limited-drops",
      price: 1299,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-utility-jacket",
      badge: "Limited",
    },
    {
      id: "derz-mens-004",
      name: "DERZ Relaxed Shirt",
      slug: "derz-relaxed-shirt",
      category: "Shirts",
      style: "casual",
      collection: "new-arrivals",
      price: 749,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-relaxed-shirt",
    },
    {
      id: "derz-mens-005",
      name: "DERZ Cargo Pants",
      slug: "derz-cargo-pants",
      category: "Bottoms",
      style: "streetwear",
      collection: "core",
      price: 999,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-cargo-pants",
    },
    {
      id: "derz-mens-006",
      name: "DERZ Graphic Tee",
      slug: "derz-graphic-tee",
      category: "T-Shirts",
      style: "streetwear",
      collection: "new-arrivals",
      price: 599,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-graphic-tee",
    },
    {
      id: "derz-mens-007",
      name: "DERZ Track Jacket",
      slug: "derz-track-jacket",
      category: "Jackets",
      style: "casual",
      collection: "core",
      price: 1099,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-track-jacket",
    },
    {
      id: "derz-mens-008",
      name: "DERZ Everyday Sweatshirt",
      slug: "derz-everyday-sweatshirt",
      category: "Hoodies",
      style: "everyday",
      collection: "core",
      price: 799,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-everyday-sweatshirt",
    },
    {
      id: "derz-mens-009",
      name: "DERZ Core Polo",
      slug: "derz-core-polo",
      category: "Shirts",
      style: "everyday",
      collection: "core",
      price: 699,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1625910513413-5fc45a5b2f02?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-core-polo",
    },
    {
      id: "derz-mens-010",
      name: "DERZ Wide Leg Trousers",
      slug: "derz-wide-leg-trousers",
      category: "Bottoms",
      style: "casual",
      collection: "new-arrivals",
      price: 899,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-wide-leg-trousers",
    },
    {
      id: "derz-mens-011",
      name: "DERZ Drop Tee",
      slug: "derz-drop-tee",
      category: "T-Shirts",
      style: "streetwear",
      collection: "limited-drops",
      price: 649,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-drop-tee",
      badge: "Drop",
    },
    {
      id: "derz-mens-012",
      name: "DERZ Signature Hoodie",
      slug: "derz-signature-hoodie",
      category: "Hoodies",
      style: "streetwear",
      collection: "new-arrivals",
      price: 949,
      currency: "ZAR",
      image:
        "https://images.unsplash.com/photo-1508170754725-6e9a5cfaa304?auto=format&fit=crop&w=900&q=80",
      href: "/product/derz-signature-hoodie",
    },
  ],
};
